SELECT E.TITLE,
 Isnull(E.SURNAME,
 '') + ' ' + Isnull(E.FIRSTNAME,
 '') + ' ' + Isnull(E.OTHERNAMES,
 '') NAME,
 E.EMPLOYER_NAME,
 E.PIN,
 E.EMPLOYER_ADDRESS,
 A.AGENT_NAME,
 A.MOBILE_PHONE as AGENT_MOBILE,
 E.UPLOAD_DATE,
  CASE 

  WHEN E.GENDER ='F' THEN 'FEMALE'
  WHEN E.GENDER ='M' THEN 'MALE'
  ELSE 'NO GENDER'
  END SEX,
 
 E.MOBILE_PHONE,
  CASE 

  WHEN E.EMPLOYER_RCNO LIKE '%PU%' THEN 'PUBLIC'
  WHEN E.EMPLOYER_RCNO LIKE '%ST%' THEN 'STATE'
  ELSE 'PRIVATE'
  
  END SECTOR,
 E.AGENT_CODE,
 E.EMPLOYER_RCNO,
B.DESCRIPTION AS BRANCH_CODE
 FROM EMPLOYEES E
 LEFT JOIN AGENT A ON A.AGENT_CODE=E.AGENT_CODE
 LEFT JOIN EMPLOYER_DETAILS ED ON ED.RCNO=E.EMPLOYER_RCNO
 LEFT JOIN BRANCH B ON B.CODE= E.BRANCH_CODE
 WHERE E.PIN NOT LIKE '%DBA%' AND PIN LIKE'%PEN%'
---AND E.UPLOAD_DATE BETWEEN @DateFrom AND @DateTo
 
 AND E.TITLE NOT LIKE '%NULL%'
 --AND A.AGENT_NAME NOT LIKE '%NULL%'
 --ORDER BY A.AGENT_NAME ASCa