SELECT E.TITLE,
 Isnull(E.SURNAME,
 '') + ' ' + Isnull(E.FIRSTNAME,
 '') + ' ' + Isnull(E.OTHERNAMES,
 '') NAME,
 E.EMPLOYER_NAME,
 E.PIN,
 E.EMPLOYER_ADDRESS,
 A.AGENT_NAME,
 A.MOBILE_PHONE as AGENT_MOBILE,
 E.DATE_CREATED,
 E.MOBILE_PHONE,
 ABS (DATEDIFF(day,GETDATE(), DATE_CREATED )) AS DURATION

 FROM EMPLOYEES E
 LEFT JOIN AGENT A ON A.AGENT_CODE=E.AGENT_CODE
 WHERE E.PIN NOT LIKE '%PEN%' AND E.PIN NOT LIKE '%DBA%'
 --AND E.DATE_CREATED BETWEEN @DateFrom AND @DateTo
 AND E.TITLE NOT LIKE '%NULL%'
 --AND A.AGENT_NAME NOT LIKE '%NULL%'
 --ORDER BY A.AGENT_NAME ASC
