USE PFA;
select * from EMPLOYEES
where pin like 'PEN%' AND PIN_INVALID<>1


SELECT TOP 100 AMOUNT, CB.NARRATION,C.VALUE_DATE, CONTRIBUTION_DATE, PRICE, C.TRANS_UNITS_R, TRANS_UNITS_V, C.* FROM CONTRIBUTION C 
INNER JOIN  CONTRIBUTION_BATCH CB ON C.BATCH_ID = CB.BATCH_ID
INNER JOIN SCHEDULES S ON S.REFNO = CB.REFNO

SELECT * FROM EMPLOYER_DETAILS


SELECT * FROM SCHEDULES