use pfa;
select EP.PIN,REG_NO,ISNULL(DATE_RECEIVED,TRANS_DATE) AS DATE_RECEIVED,ISNULL(FINAL_SALARY,0) as FINAL_SALARY,
--isnull(DATE_RETIRED,DateAdd)AS DATE_RETIRED,
TRANS_DATE,EP.ACCOUNTNAME,RSA_BALANCE,DATEOFBIRTH,
isnull(DATE_RETIRED, DATEADD(YEAR,20,DATE_OF_FIRST_APPOINTMENT))AS DATE_RETIRED,DATE_OF_FIRST_APPOINTMENT,ISNULL(EMPLOYER_CODE,EMPLOYER_RCNO) as EMPLOYER_CODE,
ET.DESCRIPTION as EXIT_TYPE,EPP.DESCRIPTION AS PAYMENT_TYPE
from EXIT_PROCESS_REGISTRATION EP
 LEFT JOIN EXIT_TYPE ET ON ET.CODE=EP.EXIT_TYPE
 LEFT JOIN EXIT_PROCESS_PAYMENT_TYPE EPP ON EPP.CODE=EP.PAYMENT_TYPE
 --JOIN EMLOYEES PIN WITH EXIT PAYMENT TO GET 
 INNER JOIN EMPLOYEES E ON EP.PIN=E.PIN
 
 



 CREATE VIEW EXIT_TYPE AS
SELECT PIN,REG_NO FROM EXIT_PROCESS_REGISTRATION
 
 SELECT EMPLOYER_RCNO,* FROM EMPLOYEES
 SELECT *FROM EXIT_PROCESS_REGISTRATION

 SELECT  * FROM EXIT_PROCESS_PAYMENT_TYPE
 EXIT_PROCESS_REGISTRATION
 