use PFA;
select E.PIN, isnull(E.SURNAME,'') +' '+ isnull(E.FIRSTNAME,'') +' '+ isnull (E.OTHERNAMES,'') AS EMPLOYEE_NAME,
CASE
WHEN GENDER  ='F' THEN 'FEMALE' 
WHEN GENDER = 'M' THEN 'MALE'
ELSE 'NO GENDER'
END GENDER,
DATE_OF_BIRTH,MARITAL_STATUS_CODE,STATE_OF_ORIGIN,EMPLOYER_CITY,EMPLOYER_NAME,EMPLOYER_RCNO,
EMPLOYER_BUSINESS,A.AGENT_CODE,A.AGENT_NAME,DESIGNATION,

CASE 
WHEN MARITAL_STATUS_CODE='M' THEN 'MARRIED'
WHEN MARITAL_STATUS_CODE ='S' THEN 'SINGLE'
ELSE 'DIVORCE'
END MARITAL_STATUS,

 CASE
 WHEN EMPLOYER_RCNO = '%PU%' THEN 'PUBLIC'
 WHEN EMPLOYER_RCNO = '%PR%' THEN 'PRIVATE'
 ELSE 'BRANCH'
 END SECTOR

FROM AGENT,CONTRIBUTION,
EMPLOYEES E
INNER JOIN CONTRIBUTION C ON C.PIN=E.PIN
INNER JOIN AGENT A ON A.AGENT_CODE=E.AGENT_CODE
WHERE E.PIN LIKE '%PEN%' AND C.PIN LIKE '%PEN%'




SELECT * FROM EMPLOYEES E

SELECT * FROM CONTRIBUTION
USE PFA;
SELECT PIN,SURNAME,FIRSTNAME,OTHERNAMES, EMPLOYER_NAME,GENDER,DATE_OF_BIRTH,MARITAL_STATUS_CODE,STATE_OF_ORIGIN,
EMPLOYER_CITY,EMPLOYER_RCNO,EMPLOYER_BUSINESS,AGENT_NAME,DESIGNATION,UPLOAD_DATE
FROM EMPLOYEES E,
AGENT 
WHERE PIN LIKE '%PEN%'

